<?php

class AppHttpException extends Exception
{
//    private $_code;
//
//    public function __construct(
//        $httpCode,
//        $message = "",
//        $code = 0,
//        Exception $previous = null
//    ) {
//        $this->_code = $httpCode;
//        parent::__construct($message, $code,
//            $previous); // TODO: Change the autogenerated stub
//    }

}